name: Push to azure

on: push

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          ref: 'master'

      - run: |
          git config --global user.email "github@rootstack.com"
          git config --global user.name "Github deployment"
          git checkout master
          git push -u https://campdeployment:LKNWLKejqw!@campdrupalsite.scm.azurewebsites.net/CampDrupalSite.git master
